export const GET_PROFILE_SUCCESS = '@GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILED = '@GET_PROFILE_FAILED';
export const UPDATE_PROFILE_SUCCESS = '@UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILED = '@UPDATE_PROFILE_FAILED';

// 
export const GET_PRODUCT_SUCCESS = '@GET_PRODUCT_SUCCESS ';
export const GET_PRODUCT_FAILED = '@GET_PRODUCT_FAILED';

//
export const GET_BANNER_SUCCESS  = '@GET_BANNER_SUCCESS';
export const GET_BANNER_FAILED  = '@GET_BANNER_FAILED';
//
export const GET_CATEGORIES_SUCCESS  = '@GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILED = '@GET_CATEGORIES_FAILED';


