// PROFILE_AKUN
export const GET_PROFILE = '@GET_PROFILE';
export const GET_PROFILE_FAILED = '@GET_PROFILE_FAILED';

export const UPDATE_PROFILE = '@UPDATE_PROFILE';
export const UPDATE_PROFILE_FAILED = '@UPDATE_PROFILE_FAILED';
