export const GET_PROFILE_SUCCESS = '@GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILED = '@GET_PROFILE_FAILED';
export const UPDATE_PROFILE_SUCCESS = '@UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILED = '@UPDATE_PROFILE_FAILED';

export const GET_PRODUCT = '@GET_PRODUCT';

